### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by nicholasVilela** [nicholasVilela/assignments#30]
# Key areas of Information to include:

## Contact information
- [ ] Email
- [ ] Phone Number (Google numbers are great if you want to protect your personal number)
- [ ] Github link
- [ ] Portfolio link

## Summary
- [ ] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [ ] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [ ] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [ ] Write where you went college and your degree.
- [ ] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [ ] Upload or submit a link to your resume for review.

**Comment by nicholasVilela** [comment]
[my-resume (1).docx](https://github.com/nicholasVilela/assignments/files/3652306/my-resume.1.docx)

**Comment by ktrammell95** [comment]
Nicholas,

I'm gonna be blunt cus I think you can take it. You are way too smart and this resume doesn't do anything to show it off. I know you might not be looking for something now but this resume can be a starter doc for you for one day when you do want to move to another position.

Ok so here goes the info and screenshots...

For starters, you don't have to use your whole address unless you really want to. I would also see about moving your GitHub and LinkedIn info up with your contact info to keep it all together and not waste space

Give more information about what projects you have worked on.

I don't do this for everyone cus they would think I was nice but look at this as an example using your info, https://docs.google.com/document/d/1AbsES_ic94qlf_z_IUq7UKZtsDeX3x7ncovHo6JsMls/edit?usp=sharing

**Comment by nicholasVilela** [comment]
Thank you so much Katherine! I just now saw this apologies for that. I'll give my resume another go and see if I can do a better job
